#!/usr/bin/python
'''
systemupgrade
'''
import click

from utils import commands
from utils import paths



@click.command()
@click.option('-nsr', '--no-sync-repo', 'no_sync_repo', type=bool, default=False, show_default=True, is_flag=True, help='Disable sync from repo.')
@click.option('-fsr', '--force-sync-repo', 'is_force_sync_repo', type=bool, default=False, show_default=True, is_flag=True, help='Force sync from repo.')
@click.option('-m', '--modify', 'is_modify', type=bool, default=False, show_default=True, is_flag=True, help='Modify the configurations.')
@click.option('-osm', '--only-sync-mirrors', 'is_only_sync_mirrors', type=bool, default=False, show_default=True, is_flag=True, help='Only sync mirrors')
@click.option('-orm', '--only-rank-mirrors', 'is_only_rank_mirrors', type=bool, default=False, show_default=True, is_flag=True, help='Only rank mirrors')
@click.option('-nsm', '--no-sync-mirrors', 'no_sync_mirrors', type=bool, default=False, show_default=True, is_flag=True, help='Disable sync mirrors')
@click.option('-nrm', '--no-rank-mirrors', 'no_rank_mirrors', type=bool, default=False, show_default=True, is_flag=True, help='Disable rank mirrors')
def _main(no_sync_repo, is_force_sync_repo, is_modify, is_only_sync_mirrors, is_only_rank_mirrors, no_sync_mirrors, no_rank_mirrors):
    '''
    Upgrade the system and clean the packages
    '''
    is_sync_repo = not no_sync_repo

    folder_path = paths.folder_path(paths.resolve_link_path(__file__))

    if is_sync_repo:
        commands.run(f"python {paths.resolve_path(folder_path, 'sync.py')} {is_force_sync_repo}", True)
    commands.run(f"python {paths.resolve_path(folder_path, 'system_upgrade.py')} {is_modify} {is_only_sync_mirrors} {is_only_rank_mirrors} {no_sync_mirrors} {no_rank_mirrors}", True)



if __name__ == '__main__':
    # pylint: disable-next=no-value-for-parameter
    _main()
